name: Build e Release do TadeuBooter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Dar permissão de execução ao gradlew
        run: chmod +x gradlew

      - name: Configurar o JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: gradle

      - name: Compilar o projeto com Gradle (sem testes)
        run: ./gradlew clean assemble -x test

      - name: Executar testes
        run: ./gradlew test

      - name: Extrair versão do build.gradle
        id: get_version
        run: |
          VERSION=$(./gradlew properties -q | grep "^version:" | awk '{print $2}')
          echo "$VERSION" > version.txt
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Salvar versão para o próximo job
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: version.txt

      - name: Publicar artefato do JAR
        uses: actions/upload-artifact@v4
        with:
          name: tadeuBooter-${{ env.VERSION }}
          path: build/libs/*.jar

  release:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Baixar a versão salva
        uses: actions/download-artifact@v4
        with:
          name: version
          path: .

      - name: Definir variável de versão
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Baixar o JAR compilado
        uses: actions/download-artifact@v4
        with:
          name: tadeuBooter-${{ env.VERSION }}
          path: build/libs/

      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: "v${{ env.VERSION }}"
          files: build/libs/*.jar
          body: "Versão ${{ env.VERSION }} do TadeuBooter"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
